version: "3.3"

services:
  psql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init_test.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: 123456
    command: postgres -c max_locks_per_transaction=2000
    networks:
      - dichori_test
  gateway_test:
    ports:
      - 7000:7000
    build:
      dockerfile: Dockerfile.dev
      context: "./services/gateway"
    volumes:
      - /app/node_modules
      - ./services/gateway:/app
    environment:
      - HOST=localhost
      - PORT=7000
      - SECRET_KEY=secret!
      - DATABASE_URL=postgres://postgres:123456@psql:5432/postgres
      - USE_SSL= false
    depends_on:
      - psql
    networks:
      - dichori_test
networks:
  dichori_test:
