CREATE DATABASE dichori WITH OWNER postgres;
CREATE TABLE usr(
  id serial PRIMARY KEY, 
  username VARCHAR(255) NOT NULL, 
  email VARCHAR(255) NOT NULL, 
  password VARCHAR(255) NOT NULL
);
CREATE TABLE post(
  id serial PRIMARY KEY, 
  title_gr VARCHAR(255) NOT NULL, 
  title_en VARCHAR(255) NOT NULL, 
  content_gr TEXT, 
  content_en TEXT, 
  summary_gr VARCHAR(255),
  summary_en VARCHAR(255),
  image_public_id VARCHAR(255),
  created_at TIMESTAMP NOT NULL, 
  updated_at TIMESTAMP , 
  author_id INTEGER NOT NULL, 
  editor_id INTEGER, 
  FOREIGN KEY (author_id) REFERENCES usr (id), 
  FOREIGN KEY (editor_id) REFERENCES usr (id)
);
CREATE TABLE category(
  id serial PRIMARY KEY, 
  name_gr VARCHAR(255) NOT NULL, 
  name_en VARCHAR(255) NOT NULL, 
  description_gr TEXT, 
  description_en TEXT,
  summary_gr VARCHAR(255),
  summary_en VARCHAR(255),
  image_public_id VARCHAR(255),
  created_at TIMESTAMP NOT NULL, 
  updated_at TIMESTAMP , 
  author_id INTEGER NOT NULL, 
  editor_id INTEGER, 
  FOREIGN KEY (author_id) REFERENCES usr (id), 
  FOREIGN KEY (editor_id) REFERENCES usr (id)
);
CREATE TABLE service(
  id serial PRIMARY KEY, 
  name_gr VARCHAR(255) NOT NULL, 
  name_en VARCHAR(255) NOT NULL, 
  content_gr TEXT, 
  content_en TEXT, 
  price DECIMAL,
  category_id INTEGER NOT NULL,
  summary_gr VARCHAR(255),
  summary_en VARCHAR(255),
  image_public_id VARCHAR(255),
  created_at TIMESTAMP NOT NULL, 
  updated_at TIMESTAMP , 
  author_id INTEGER NOT NULL, 
  editor_id INTEGER, 
  FOREIGN KEY (category_id) REFERENCES category (id),
  FOREIGN KEY (author_id) REFERENCES usr (id), 
  FOREIGN KEY (editor_id) REFERENCES usr (id)
);
CREATE TABLE member(
  id serial PRIMARY KEY, 
  name_gr VARCHAR(255) NOT NULL, 
  name_en VARCHAR(255) NOT NULL, 
  description_gr TEXT, 
  description_en TEXT,
  summary_gr VARCHAR(255),
  summary_en VARCHAR(255),
  position_gr VARCHAR(255),
  position_en VARCHAR(255),
  image_public_id VARCHAR(255),
  created_at TIMESTAMP NOT NULL, 
  updated_at TIMESTAMP , 
  author_id INTEGER NOT NULL, 
  editor_id INTEGER, 
  FOREIGN KEY (author_id) REFERENCES usr (id), 
  FOREIGN KEY (editor_id) REFERENCES usr (id)
);
CREATE TABLE subscriber(
   id serial PRIMARY KEY, 
   email VARCHAR(255) NOT NULL
);
CREATE TABLE page(
  id serial PRIMARY KEY,
  title_en VARCHAR(255) NOT NULL, 
  title_gr VARCHAR(255) NOT NULL, 
  content_en TEXT,
  content_gr TEXT,
  image_public_id VARCHAR(255),
  url VARCHAR(255),
  created_at TIMESTAMP NOT NULL, 
  updated_at TIMESTAMP , 
  author_id INTEGER NOT NULL, 
  editor_id INTEGER, 
  FOREIGN KEY (author_id) REFERENCES usr (id), 
  FOREIGN KEY (editor_id) REFERENCES usr (id)
);

CREATE TABLE settings(
  id serial PRIMARY KEY, 
  header_menu_config JSONB,
  footer_menu_config JSONB,
  home_title_en VARCHAR(255), 
  home_title_gr VARCHAR(255), 
  home_content_en TEXT,
  home_content_gr TEXT
);

CREATE TABLE event(
  id serial PRIMARY KEY, 
  title_en VARCHAR(255), 
  title_gr VARCHAR(255), 
  content_en TEXT,
  content_gr TEXT,
  event_start TIMESTAMP,
  event_end TIMESTAMP,
  created_at TIMESTAMP NOT NULL, 
  updated_at TIMESTAMP , 
  author_id INTEGER NOT NULL, 
  editor_id INTEGER,
  FOREIGN KEY (author_id) REFERENCES usr (id), 
  FOREIGN KEY (editor_id) REFERENCES usr (id)
);

INSERT INTO settings(header_menu_config,footer_menu_config,home_title_en,home_title_gr,home_content_en,home_content_gr)
VALUES
  (
    '{"items":[]}','{"items":[]}','','','',''
  );



INSERT INTO usr(username, email, password) 
VALUES 
  (
    'a_loop_is', 'manos.aloupis@gmail.com', 
    '$2b$10$ahs7h0hNH8ffAVg6PwgovO3AVzn1izNFHn.su9gcJnUWUzb2Rcb2W' -- = ssseeeecrreeet
  );

  INSERT INTO usr(username, email, password) 
  VALUES 
    (
      'chupacabra', 'chupacabra026@gmail.com', 
      '$2b$10$ahs7h0hNH8ffAVg6PwgovO3AVzn1izNFHn.su9gcJnUWUzb2Rcb2W' -- = ssseeeecrreeet
    );

insert into usr ( username, email, password) values ( 'kdudley0', 'ldrable0@senate.gov', 'Cg6dFI');
insert into usr ( username, email, password) values ( 'smafham1', 'dcorcoran1@alexa.com', 'd27Tzd');
insert into usr ( username, email, password) values ( 'lgibbs2', 'sbromfield2@privacy.gov.au', 'KXK4gwze2S3');
insert into usr ( username, email, password) values ( 'cnibley3', 'emaps3@stumbleupon.com', 'mZWiGN');
insert into usr ( username, email, password) values ( 'kromand4', 'preye4@yolasite.com', 'wIfvBRDOV');
insert into usr ( username, email, password) values ( 'tmccaighey5', 'mpakeman5@nbcnews.com', 'JFQardym');
insert into usr ( username, email, password) values ( 'gmaharg6', 'rhedditeh6@hc360.com', 'Ek8zNkAi');
insert into usr ( username, email, password) values ( 'dbagot7', 'ndifrisco7@google.cn', 'sIQuYt');
insert into usr ( username, email, password) values ( 'cmarquis8', 'bsandall8@indiatimes.com', 'XlgWFsG');
insert into usr ( username, email, password) values ( 'oschistl9', 'jpeat9@tuttocitta.it', '9H9jQE0iCTkI');



/**POSTS**/
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Woman That Dreamed About a Man, The (Kvinden der drømte om en mand)', 'Satan Met a Lady', 'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2020-10-14T14:54:40Z', '2021-08-28T11:28:51Z', 11, 12);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Tom, Tom, the Piper''s Son', 'Burning Plain, The', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.', '2021-07-08T21:49:53Z', '2021-04-29T11:48:33Z', 1, 1);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Lulu in Berlin', 'House of Sand and Fog', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 'Suspendisse potenti.', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '2021-07-17T16:58:14Z', '2021-07-17T09:59:24Z', 1, 1);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Get Over It', 'I Married A Strange Person!', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Nulla justo.', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', '2021-07-08T16:16:53Z', '2021-07-07T06:04:32Z', 10, 5);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Killing Room, The', 'Caught Up', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Phasellus in felis.', 'In hac habitasse platea dictumst.', '2021-03-01T18:08:21Z', '2020-10-09T08:21:49Z', 6, 9);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Man to Man', 'Topaze', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'Nulla tellus. In sagittis dui vel nisl.', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2021-01-24T16:33:15Z', '2021-02-03T02:56:27Z', 6, 4);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Light It Up', 'Night the Lights Went Out in Georgia, The', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'Nulla tempus.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '2021-01-23T17:06:49Z', '2021-04-23T09:02:26Z', 9, 11);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Delta Farce', 'Two Women', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Nulla tellus. In sagittis dui vel nisl.', 'Pellentesque at nulla. Suspendisse potenti.', '2020-09-12T05:54:50Z', '2020-11-26T07:04:33Z', 3, 10);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Alien Outpost', 'End, The', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque.', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-10-02T19:24:01Z', '2021-06-10T16:46:37Z', 4, 10);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Man with the Iron Fists, The', 'Barefoot Contessa, The', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'Nullam molestie nibh in lectus.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', '2021-08-20T02:20:52Z', '2021-07-29T16:02:46Z', 4, 12);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Little Italy', 'Prime Suspect: Inner Circles', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Mauris ullamcorper purus sit amet nulla.', '2020-11-29T08:32:47Z', '2021-01-17T03:31:32Z', 9, 9);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('High on Crack Street: Lost Lives in Lowell', 'I Am Jesus', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus.', 'Suspendisse accumsan tortor quis turpis.', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-12-23T22:42:38Z', '2021-01-12T07:35:46Z', 7, 3);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Where''s Marlowe?', 'Shark Tale', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.', 'Duis mattis egestas metus. Aenean fermentum.', 'Aenean fermentum.', '2021-02-24T19:01:16Z', '2020-11-26T01:19:51Z', 1, 8);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Nobody Knows Anything!', 'Daylight (Daglicht)', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Donec semper sapien a libero. Nam dui.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', '2021-09-03T16:11:47Z', '2021-05-12T08:21:08Z', 10, 1);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Laura', 'Nina Takes a Lover', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Morbi non quam nec dui luctus rutrum.', '2021-08-01T07:04:44Z', '2021-02-12T21:56:14Z', 4, 6);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Model', 'Undiscovered', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.', 'In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Etiam justo. Etiam pretium iaculis justo.', 'Duis bibendum.', '2021-03-21T08:21:18Z', '2021-03-09T00:11:35Z', 4, 10);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Cow, The (Gaav)', 'September Issue, The', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.', 'In quis justo.', 'Quisque porta volutpat erat.', '2021-08-31T01:12:29Z', '2021-05-13T20:50:58Z', 12, 10);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Tribe, The (Plemya)', 'Brothers Grimm, The', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.', 'Phasellus sit amet erat. Nulla tempus.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', '2020-09-29T11:54:43Z', '2021-01-26T15:46:32Z', 9, 8);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('The Army', 'Across the Bridge', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Vivamus tortor.', 'Suspendisse ornare consequat lectus.', '2021-06-29T16:19:00Z', '2021-08-08T18:28:23Z', 2, 9);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Sexual Life', 'Takva: A Man''s Fear of God', 'Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit.', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Integer a nibh. In quis justo.', '2020-12-04T17:43:44Z', '2020-10-24T11:09:11Z', 11, 10);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Kai Po Che!', 'City Slickers', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', '2021-02-11T07:09:06Z', '2020-11-01T13:19:02Z', 2, 8);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Bring It On: Fight to the Finish', 'Comic Book Confidential', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Aliquam sit amet diam in magna bibendum imperdiet.', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', '2021-08-18T00:31:12Z', '2020-10-17T18:23:57Z', 2, 8);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('The Butterfly Effect 3: Revelations', 'Left Behind', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', '2021-06-01T09:56:25Z', '2021-06-16T14:22:47Z', 1, 4);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Freeway', 'Yellow Sky', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', '2021-08-26T16:27:49Z', '2021-07-08T15:59:37Z', 12, 5);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Shadow Warriors 2 (Assault on Devil''s Island)', 'Nothing Sacred', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'Aenean fermentum.', '2021-05-16T05:03:26Z', '2021-08-24T15:02:48Z', 12, 11);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Kiss of Death', 'Down with Love', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'Nunc rhoncus dui vel sem. Sed sagittis.', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', '2021-07-27T08:37:12Z', '2020-10-06T12:07:15Z', 6, 4);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Daddy Long Legs', 'Sun Shines Bright, The', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.', 'Aliquam non mauris.', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', '2020-12-24T06:11:27Z', '2021-07-07T17:13:26Z', 12, 2);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Princess Bride, The', 'Escape from the Planet of the Apes', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', '2020-11-23T06:36:58Z', '2020-10-02T19:24:56Z', 8, 2);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Yellow Sea, The (a.k.a. The Murderer) (Hwanghae)', 'Stranded', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Maecenas pulvinar lobortis est.', '2021-08-19T12:04:51Z', '2020-10-23T18:13:52Z', 9, 4);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Camille Claudel', 'Home', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.', '2021-03-29T01:07:20Z', '2021-06-28T20:12:15Z', 6, 9);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Amour', 'Devil Commands, The', 'Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio.', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Proin at turpis a pede posuere nonummy. Integer non velit.', '2021-09-03T02:22:43Z', '2021-01-31T20:50:18Z', 3, 12);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Stoked: The Rise and Fall of Gator', 'American Strays', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus.', 'Vestibulum ac est lacinia nisi venenatis tristique.', 'Suspendisse accumsan tortor quis turpis.', '2021-02-14T14:10:53Z', '2021-08-06T21:00:59Z', 10, 6);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Gambling City', 'Whip Hand, The', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 'Suspendisse potenti.', '2021-05-01T09:59:28Z', '2020-12-16T09:20:14Z', 5, 1);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Antiviral', 'Stone Reader', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', 'Morbi ut odio.', '2021-01-12T21:37:55Z', '2021-01-18T09:02:38Z', 10, 11);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Oh, God! You Devil', 'Unfinished Song (Song for Marion)', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti.', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.', '2020-09-26T17:27:59Z', '2021-03-29T07:51:08Z', 11, 2);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Breakin''', 'Four Daughters', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.', 'Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'Nullam porttitor lacus at turpis.', 'Etiam justo.', '2021-05-25T10:27:40Z', '2020-10-06T13:27:26Z', 7, 1);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('The Man Who Could Cheat Death', 'The Mule', 'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', '2020-11-04T10:41:16Z', '2021-04-24T22:39:30Z', 12, 8);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Veer Zaara', 'I Saw Mommy Kissing Santa Claus', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', '2020-10-04T10:57:22Z', '2021-03-18T00:13:00Z', 5, 10);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Monsters vs Aliens: Mutant Pumpkins from Outer Space', 'Twelve O''Clock High', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc.', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2021-04-17T07:50:13Z', '2020-10-25T05:25:50Z', 5, 6);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Over the Hedge', 'Slumber Party Massacre III', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Donec semper sapien a libero.', 'Duis aliquam convallis nunc.', '2020-12-24T10:12:43Z', '2021-02-13T19:52:46Z', 9, 6);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Jarhead', 'Big Trouble', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.', 'Curabitur at ipsum ac tellus semper interdum.', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', '2021-01-03T11:37:46Z', '2020-09-15T10:11:38Z', 12, 10);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Modulations', 'Reel Rock 8 ', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna.', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.', 'Aenean sit amet justo.', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', '2021-05-11T14:03:42Z', '2021-04-14T23:25:31Z', 9, 11);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Young Winston', 'Coming Apart', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'Donec semper sapien a libero. Nam dui.', 'Pellentesque eget nunc.', '2021-05-02T12:26:56Z', '2020-12-10T13:18:52Z', 6, 8);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Beyond Justice', 'Delbaran', 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2021-02-26T09:33:09Z', '2020-11-08T21:34:34Z', 10, 3);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('The Third Reich: The Rise & Fall', 'Postman Always Rings Twice, The', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.', 'Vestibulum rutrum rutrum neque.', 'Quisque id justo sit amet sapien dignissim vestibulum.', '2021-02-05T20:35:53Z', '2021-08-09T11:36:16Z', 6, 8);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Dance of the Dead', 'Bear''s Kiss', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Etiam vel augue. Vestibulum rutrum rutrum neque.', 'Quisque id justo sit amet sapien dignissim vestibulum.', '2021-07-16T13:25:41Z', '2020-12-26T05:37:25Z', 11, 6);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Hot Spot, The', 'Lethal Weapon 4', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.', 'Nullam molestie nibh in lectus. Pellentesque at nulla.', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '2021-03-05T04:51:42Z', '2021-08-21T08:16:32Z', 2, 4);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('State of Emergency', 'Fallen Art (Sztuka spadania)', 'Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.', 'Etiam vel augue.', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2021-05-19T21:56:09Z', '2021-03-15T09:06:21Z', 12, 7);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Wadd: The Life & Times of John C. Holmes', 'Darkman', 'Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'In hac habitasse platea dictumst.', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', '2021-03-28T05:13:50Z', '2020-10-29T15:06:14Z', 7, 6);
insert into post (title_gr, title_en, content_en, content_gr, summary_en, summary_gr, created_at, updated_at, author_id, editor_id) values ('Gospa', 'Manson', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum.', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.', '2021-01-13T21:18:00Z', '2020-10-13T03:16:37Z', 11, 11);
